### PR TITLE
Th add pet

### PR DESCRIPTION
**Pull request by TimothyHarley**

### CODE REVIEW

**Comment by JonathanPMohan** [comment]
👍  Looks good to me at first glance.  I haven't tested it though, tied up with the fathers day festivities at the moment. I'll test it more later to be sure.

**Comment by MCrank** [comment]
@TimothyHarley The Add pet is working mostly.  I am not getting the Burial Address information as looks like it is tied to the CreatePetRequest model which does not have that information.
image

So I think on the CreatePetRequest model we want to add all of the Address information.  One other thought would be to look into adding Date Pickers for the Birth/Death date.  Those will allow us to endure that the dates are formatted properly and the user won't have to guess the format to put the data into.  maybe not this go around but I definitely think we should do that else our Date data is probably going to be all screwey if I know how users are.

**Comment by MCrank** [comment]
Also if you make your petRepository method take a type of CreatePetRequest you won't need to send in all of the paramters individually.  You can just pass the object around.  If that makes sense?

image

Here is the AddUser method in the User repository where I am taking in a CreateUserRequest object if that helps explain.  Yours is not wrong by any means.  Just wanted to point it out so to maybe save some time writing the code.

image

**Comment by JonathanPMohan** [comment]
Well.... Marco...I think you pretty much summed it up well. looks like a quick fix whichever way you slice it.

**Comment by MCrank** [comment]
👍 @TimothyHarley Pets are adding.  

One small thing we can look at tonight is getting the new pets to refresh after we added them.  @JonathanPMohan is having the same issue and we are about to take a look.  I'd say safe to merge in from my POV.

**Pull request merged**
